### ISSUE TITLE
Cannot download apk

### ISSUE THREAD

**Issue by Radzhab** [dflower/google-play-crawler#2]
I want download apl. 

write this command 

python download.py com.google.android.gm
          but its return error. 

Traceback (most recent call last):
  File "download.py", line 38, in <module>
    data = api.download(packagename, vc, ot)
  File "C:\Python27\googleplay.py", line 267, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.
downloadAuthCookie[0]
  File "C:\Python27\lib\site-packages\google\protobuf\internal\containers.py", l
ine 64, in **getitem**
    return self._values[key]
IndexError: list index out of range

**Comment by dflower** [comment]
Hi, did you edit config.py before using the provided scripts?

**Comment by mj170420** [comment]
We have completed up to authentication and have successfully got authenticated but after that when we uncommented one of the commented lines
"getApps(api,'GAME','apps_topselling_free','100',None)"
by running 
"python crawler.py"
we have got error
"Traceback (most recent call last):
  File "crawler.py", line 72, in <module>
    getApps(api,'GAME','apps_topselling_free','100',None)
  File "crawler.py", line 29, in getApps
    doc = message.doc[0]
IndexError: list index out of range" 
Please Help
Also it will be very helpful if u can tell us the format of token and its length and an example if any of that token
