### ISSUE TITLE
All commands fail even when setting config.py correctly

### ISSUE THREAD

**Issue by kmicinski** [dflower/google-play-crawler#3]
Is the crawler simply broken at this point?

```
python categories.py
/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "categories.py", line 15, in <module>
    api.login(GOOGLE_LOGIN, GOOGLE_PASSWORD, AUTH_TOKEN)
  File "/Users/micinski/projects/google-play-crawler/googleplay.py", line 135, in login
    raise LoginError("server says: " + params["error"])
googleplay.LoginError: u'server says: BadAuthentication'
```

**Comment by syrian-dev** [comment]
me too same error

`  File "download.py", line 28, in <module>
    api.login(GOOGLE_LOGIN, GOOGLE_PASSWORD, AUTH_TOKEN)
  File "/root/googleplay-api/googleplay.py", line 135, in login
    raise LoginError("server says: " + params["error"])
googleplay.LoginError: u'server says: BadAuthentication'`

**Comment by Suneal** [comment]
So this never got fixed?
