### ISSUE TITLE
download.py is not working

### ISSUE THREAD

**Issue by ithomaslin** [dflower/google-play-crawler#4]
When trying to run the download.py, it prints out the following (the config.py file is modified as required):
Downloading to file com.meitu.wheecam_0.apk with size 0.0bytes...
Traceback (most recent call last):
  File "download.py", line 46, in <module>
    data = api.download(packagename, vc, ot)
  File "/Users/tolin/Downloads/googleplay-api-master/googleplay_api/googleplay.py", line 315, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/containers.py", line 64, in **getitem**
    return self._values[key]
IndexError: list index out of range

**Comment by gowtham1984** [comment]
Facing similar issue. Is there any setting we need to do with our Google Account ?
